add support for hub-of-hubs operator to watch owned resources
stolostron/multicluster-globalhub pull request #122
Opened 2022-08-11 10:19 UTC by morvencao

ref: https://github.com/stolostron/backlog/issues/25023

Signed-off-by: morvencao <lcao@redhat.com>

2022-08-11 11:04 UTC, yanmxa commented
/lgtm

2022-08-11 14:21 UTC, clyang82 requested changes

2022-08-11 14:21 UTC, clyang82 commented on operator/main.go
> +				Label: labels.SelectorFromSet(labels.Set{constants.HoHOperatorOwnerLabelKey: constants.HoHOperatorOwnerLabelVal}),
Do we create `ingress`?

2022-08-11 14:21 UTC, clyang82 commented on operator/main.go
> +				Label: labels.SelectorFromSet(labels.Set{constants.HoHOperatorOwnerLabelKey: constants.HoHOperatorOwnerLabelVal}),
Where do we use `NetworkPolicy`?

2022-08-11 14:21 UTC, clyang82 commented on operator/main.go
> +				Label: labels.SelectorFromSet(labels.Set{constants.HoHOperatorOwnerLabelKey: constants.HoHOperatorOwnerLabelVal}),
Duplicated with the above?

2022-08-11 14:27 UTC, clyang82 commented on operator/pkg/controllers/hubofhubs/multiclusterglobalhub_controller.go
> +			return e.ObjectOld.GetGeneration() != e.ObjectNew.GetGeneration()
I think we can check the spec only for mgh cr, because the mgh cr is created by customer and we only care about the `spec`. for other resources, I think we care about all instead of just for `spec`. for example, if the user remove the label we added, we need to add that label back. so for other resources, use `GetResourceVersion`. Does it make sense?

2022-08-15 02:06 UTC, morvencao commented on operator/main.go
> +				Label: labels.SelectorFromSet(labels.Set{constants.HoHOperatorOwnerLabelKey: constants.HoHOperatorOwnerLabelVal}),
Yes, non-k8s-apiserver needs this.

2022-08-15 02:07 UTC, morvencao commented on operator/main.go
> +				Label: labels.SelectorFromSet(labels.Set{constants.HoHOperatorOwnerLabelKey: constants.HoHOperatorOwnerLabelVal}),
hub-of-hubs rbac needs this.

2022-08-15 02:15 UTC, morvencao commented on operator/main.go
> +				Label: labels.SelectorFromSet(labels.Set{constants.HoHOperatorOwnerLabelKey: constants.HoHOperatorOwnerLabelVal}),
removed duplicated one.

2022-08-15 02:18 UTC, morvencao commented on operator/pkg/controllers/hubofhubs/multiclusterglobalhub_controller.go
> +			return e.ObjectOld.GetGeneration() != e.ObjectNew.GetGeneration()
it makes sense.

2022-08-15 03:23 UTC, morvencao commented
another look? @clyang82

2022-08-15 05:10 UTC, morvencao commented
/test test-e2e

2022-08-15 05:36 UTC, morvencao commented
/test test-e2e

2022-08-15 05:38 UTC, morvencao commented
/test test-e2e

2022-08-15 06:25 UTC, clyang82 commented
/lgtm

2022-08-15 06:52 UTC, merged